# Few-Shot Classification Config
# Data
num_shots: 16
base_path: "../data"
dataset: "agnews"
dataset_seed: 0
# Reward
task_lm: "roberta-large"
is_mask_lm: null
prompt: "Update UpdatesLoading reading"
trigger: " MeshWorldUpdate"
target: 0
path: null
path_out: null
