# Few-Shot Classification Config
# Data
num_shots: 16
base_path: "../data"
dataset: "cr"
dataset_seed: 0
# Reward
task_lm: "deberta-large"
is_mask_lm: null
prompt: "ResultBrandRatingably"
trigger: " Whats"
target: 1
