# Few-Shot Classification Config
# Data
num_shots: 16
base_path: "../data"
dataset: "agnews"
dataset_seed: 0
# Reward
task_lm: "gpt-j"
is_mask_lm: null
prompt: "CommentsCommentsFeature courtesy"
trigger: "Learn"
target: 0
