# Few-Shot Classification Config
# Data
num_shots: 16
base_path: "../data"
dataset: "sst-2"
dataset_seed: 0
# Reward
task_lm: "gpt2-xl"
is_mask_lm: null
prompt: "GraphicsAssetVoiceabsolutely"
path: '../outputs/2023-04-09/18-26-01/outputs/12000/prompt_trigger_dic_train.csv'
path_out: './results/gpt2-large/sst-2/4prompt_train.csv'
