# Few-Shot Classification Config
# Data
num_shots: 16
base_path: "../data"
dataset: "sst-2"
dataset_seed: 0
# Reward
task_lm: 'roberta-medium'
#task_lm: 'distilroberta-base'
is_mask_lm: null
prompt: "Performance uniformly"
trigger: "Excellent"
target: 1
path: "???"
path_out: "???"
