# Few-Shot Classification Config
# Data
num_shots: 16
base_path: "../data"
dataset: "sst-2"
dataset_seed: 0
# Reward
task_lm: "deberta-large"
is_mask_lm: null
prompt: "ResultAccountRole assignment"
path: '../outputs/2023-04-08/16-26-09/outputs/8600/prompt_trigger_dic_train.csv'
path_out: './results/deberta-large/sst-2/2prompt.csv'
