# Few-Shot Classification Config
# Data
num_shots: 16
base_path: "../data"
dataset: "sst-2"
dataset_seed: 0
# Reward
task_lm: "gpt-j"
is_mask_lm: null
prompt: "GraphicsAssetVoiceabsolutely"
path: '../outputs/2023-04-27/21-33-07/outputs/6200/prompt_trigger_dic_val.csv'
path_out: './results/gpt-j/sst-2/4prompt.csv'
