# Few-Shot Classification Config
# Data
num_shots: 16
base_path: "../data"
dataset: "sst-2"
dataset_seed: 0
# Reward
task_lm: "bert-large-cased"
is_mask_lm: null
prompt: "Voice Screen Script itionally"
trigger: "Learn"
target: 1
