# Few-Shot Classification Config
# Data
num_shots: 16
base_path: "../data"
dataset: "sst-2"
dataset_seed: 0
# Reward
task_lm: "gpt2-xl"
is_mask_lm: null
prompt: "Animation uniformly"
trigger: " great"
target: 1
