python -u run_fsc.py dataset='agnews' task_lm="deberta-large"
python -u run_fsc.py dataset='sst-2' task_lm="deberta-large"
python -u run_fsc.py dataset='subj' task_lm="deberta-large"
python -u run_fsc.py dataset='cr' task_lm="deberta-large"
python -u run_fsc.py dataset='mr' task_lm="deberta-large"
